# -*- coding: utf-8 -*-
"""Prueba1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNkIV6h5Ayvm9iZRnacrzi5r5lxu9HLN
"""

import streamlit as st

st.title("Hola mundo")