# -*- coding: utf-8 -*-
"""Prueba2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9D_-PdV6AOn6lTKb4P5gT-ulyZCQFVB
"""

import streamlit as st
import pandas as pd
from streamlit_echarts import st_echarts

st.litle("Iniciar Sesion")

usuario = st.text_input("Usuario")
contraseña = st.text_input("Contraseña", type="password")

if st.button("Iniciar Sesion"):
    if usuario == "admin" and contraseña == "admin":
        st.success("Inicio de sesion exitoso")
    else:
        st.error("Inicio de sesion fallido")